"""
WriteArtifacts: persists the claim decision to S3 (three files) and DynamoDB.

S3 output structure:
  s3://{decisions_bucket}/clients/{client_id}/{claim_id}/
      decision.json       - structured decision record
      adjuster_email.md   - draft email for the adjuster to review/send
      evidence_bundle.json - full evidence + original LLM output for audit

DynamoDB record:
  PK: client_id  SK: claim_id
  All decision fields + ISO8601 created_at + TTL (90 days)
"""
import json
import os
from datetime import datetime, timezone, timedelta

import boto3

s3 = boto3.client("s3")
dynamodb = boto3.client("dynamodb")

TABLE_NAME = os.environ["DECISIONS_TABLE_NAME"]


def handler(event, context):
    client_id = event["client_id"]
    claim_id = event["claim_id"]
    decisions_bucket = event["decisions_bucket"]
    prefix = f"clients/{client_id}/{claim_id}"

    now = datetime.now(timezone.utc)
    created_at = now.isoformat()
    ttl = int((now + timedelta(days=90)).timestamp())

    # --- decision.json ---
    decision = {
        "client_id": client_id,
        "claim_id": claim_id,
        "submitted_at": event.get("submitted_at", ""),
        "processed_at": created_at,
        "final_status": event["final_status"],
        "original_recommendation": event["original_recommendation"],
        "confidence": event["confidence"],
        "override_reason": event.get("override_reason"),
        "reasoning": event["reasoning"],
        "red_flags": event["red_flags"],
        "requires_adjuster_review": event["requires_adjuster_review"],
    }
    s3.put_object(
        Bucket=decisions_bucket,
        Key=f"{prefix}/decision.json",
        Body=json.dumps(decision, indent=2).encode(),
        ContentType="application/json",
    )

    # --- adjuster_email.md ---
    draft_email = event.get("draft_email", "")
    email_md = _format_email_markdown(
        client_id, claim_id, decision, draft_email, created_at
    )
    s3.put_object(
        Bucket=decisions_bucket,
        Key=f"{prefix}/adjuster_email.md",
        Body=email_md.encode(),
        ContentType="text/markdown",
    )

    # --- evidence_bundle.json (full audit record) ---
    bundle = {
        "decision": decision,
        "llm_verdict": event.get("llm_verdict", {}),
        "evidence": event.get("evidence", {}),
    }
    s3.put_object(
        Bucket=decisions_bucket,
        Key=f"{prefix}/evidence_bundle.json",
        Body=json.dumps(bundle, indent=2).encode(),
        ContentType="application/json",
    )

    # --- DynamoDB record ---
    dynamodb.put_item(
        TableName=TABLE_NAME,
        Item={
            "client_id":              {"S": client_id},
            "claim_id":               {"S": claim_id},
            "submitted_at":           {"S": event.get("submitted_at", "")},
            "processed_at":           {"S": created_at},
            "final_status":           {"S": decision["final_status"]},
            "original_recommendation": {"S": decision["original_recommendation"]},
            "confidence":             {"N": str(decision["confidence"])},
            "requires_adjuster_review": {"BOOL": decision["requires_adjuster_review"]},
            "reasoning":              {"S": decision["reasoning"][:1000]},
            "red_flags":              {"S": json.dumps(decision["red_flags"])},
            "decision_s3_prefix":     {"S": f"s3://{decisions_bucket}/{prefix}/"},
            "ttl":                    {"N": str(ttl)},
        },
    )

    return {
        "client_id": client_id,
        "claim_id": claim_id,
        "final_status": decision["final_status"],
        "decision_s3_prefix": f"s3://{decisions_bucket}/{prefix}/",
        "requires_adjuster_review": decision["requires_adjuster_review"],
        "adjuster_email_text": email_md,
    }


def _format_email_markdown(client_id, claim_id, decision, draft_email, created_at):
    status_line = {
        "APPROVE": "Your claim has been reviewed and we are pleased to inform you of a favorable recommendation.",
        "DENY": "Your claim has been reviewed. Our adjuster will contact you to discuss the findings.",
        "NEEDS_REVIEW": "Your claim requires additional review by one of our adjusters, who will be in touch shortly.",
    }.get(decision["final_status"], "Your claim is under review.")

    red_flags_section = ""
    if decision["red_flags"]:
        flags = "\n".join(f"- {f}" for f in decision["red_flags"])
        red_flags_section = f"\n\n**Internal Notes (do not send to claimant):**\n{flags}"

    return f"""# Draft Adjuster Communication
**Claim ID:** {claim_id}
**Client:** {client_id}
**Processed:** {created_at}
**Status:** {decision['final_status']}
**Confidence:** {decision['confidence']:.0%}

> This is a DRAFT generated by the AI pipeline. Review and edit before sending.
> Do not send if override_reason is present -- escalate to supervisor first.

---

Dear Claimant,

{draft_email if draft_email else status_line}

If you have any questions regarding your claim {claim_id}, please do not hesitate to contact us.

Sincerely,
[Adjuster Name]
[Company Name] Claims Department
{red_flags_section}
"""
